language: ruby
rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - 2.0.0-p451 # OS X 10.9.4
 - 2.1.0
 - 2.1.2
 - 2.1.3
 - 2.2.0
 - ruby-head
 - jruby-18mode
 - jruby-19mode
 - jruby-head
 - rbx
 - rbx-2
 - ree
os:
  - linux
  - osx
script: rake spec
