language: ruby
rvm:
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - 2.0.0-p451 # OS X 10.9.4
 - 2.1.0
 - 2.1.2
 - 2.1.3
 - "2.1"
 - 2.2.0
 - "2.2"
 - ruby-head
 - jruby-19mode
 - jruby-head
 - rbx
 - rbx-2
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rvm: 1.9.2 # "undefined method `lazy' for []:Array"
      os: linux
    - rvm: 1.9.2 # "Requested binary installation but no rubies are available to download"
      os: osx
    - rvm: 1.9.3 # "undefined method `lazy' for []:Array"
    - rvm: "2.2" # "Requested binary installation but no rubies are available to download"
      os: osx
    - rvm: ruby-head # "undefined method `hexdigest' for #<OpenSSL::Digest:0x007fda73e3b458>"
      os: osx
    - rvm: jruby-19mode # "undefined method `lazy' for []:Array"
      os: linux
    - rvm: jruby-19mode # "Requested binary installation but no rubies are available to download"
      os: osx
    - rvm: jruby-head # 4 failures in #map
    - rvm: rbx # 5 failures
    - rvm: rbx-2 # 5 failures
env:
  - rvm_max_time_flag=60
before_install:
  - gem install bundler
  - rm Gemfile.lock
script: rake spec
